### ISSUE TITLE
Allow multiple attached buttons

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1000]
Should we allow multiple attached buttons in inputs? It would allow things like this use case:

> FeedImgUrl allows you to fetch the first image component's url (via magic-button) or browse for one using the mediaplay picker

They might look a little weird if we allowed _n-number_ of buttons. Perhaps we could limit it to 2 or 3?

**Comment by nelsonpecora** [comment]
Per [this discussion](https://github.com/JosephusPaye/Keen-UI/issues/374#issuecomment-344735193), it looks like UIDatepicker might go in the direction of always having an `x` button to clear the date, which means we'd need to de-facto support multiple buttons if we wanted to allow any attached buttons on datepicker.

**Comment by nelsonpecora** [comment]
@pfeytser what do you think? should there be some limitation (only 2 buttons, only 3 buttons, or maybe if there is more than two buttons have them in a dropdown menu)?

**Comment by pfeytser** [comment]
I think we should allow 2 buttons shown at the same time because I can think of a few other use cases off the top of my head where they could be necessary. For example, next to the date picker, you could have a "today" button and a "clear".  

Having 3 buttons seems unruly, I would suggest that's when they turn into 3 dots with drop-down.

**Comment by nelsonpecora** [comment]
Agreed. Moving this to the backlog.
