### ISSUE TITLE
Restore to published version of page

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1005]
_[added by Nelson]: In the publish drawer, maybe we should have a section / button that allows the user to revert the latest version of the page to the published version, if they have unpublished changes_

**Comment by pfeytser** [comment]
1. Grab published page json as a string, regex convert @published to latest. Save page. Reload browser. 
2. Fuckin' double confirm. Maybe by having user type the slug. 
3. Place this functionality below custom URL in publish drawer.

**Comment by nelsonpecora** [comment]
Should we do this by itself, or have it as part of the history section? e.g. the last published version would have "restore" as an action if there are unpublished changes

**Comment by pfeytser** [comment]
Add this button under latest published version in history.

**Comment by nelsonpecora** [comment]
Context: Sometimes editors making changes to a page after it has been published find themselves making unrecoverable changes (i.e. changes they can't simply undo to get back to the published version). While devs can grab the published version, replace the references, and update the latest version, it would be helpful to have an affordance in the Kiln UI to do this. Something along the lines of "revert all changes since the last publish"
