### ISSUE TITLE
Kiln Performance on Long Articles

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1006]
Example:
http://nymag.com/strategist/pages/cja01zmwc008ybfyerwmn60qn.html

Sent to me by Neil:
http://www.vulture.com/2017/09/the-star-trek-universe-a-beginners-guide.html
http://www.vulture.com/2017/09/every-stephen-king-movie-ranked-from-worst-to-best.html
http://www.vulture.com/2017/09/gossip-girl-classic-hollywood-references-ranked.html

**Comment by nelsonpecora** [comment]
This is specifically (but not exclusively) an issue with articles that contain 10 or more product components. Not sure if it's affected more by specific components, or if it scales linearly with the number of components on a page (or number of component lists).

**Comment by nelsonpecora** [comment]
I can confirm that this is an issue with selectors, and it might be a vue-related issue as they're revving up the garbage collector (which is blocking the UI from updating)

**Comment by nelsonpecora** [comment]
Ok, I updated a lot of things that seem to fix the lag on page load and when navigating around / saving stuff, especially on those large example articles:

* all `setTimeout` calls now use `requestAnimationFrame`
* updated `vue` deps to 2.5.9
* optimized `select` mouseover
* refactored `selector.vue` to prevent GC thrashing and long vue queue flushes (front-loading most of the computed properties so they can be calculated once on page load rather than every time a selector is selected)
* added `v-once` to selectors, placeholders, and other components that aren't dynamic
* optimized `keep-alive` usage across components
* removed `resize` listener from selectors, since the mouseover select/unselect means components don't stay selected long enough for us to worry about their position being wrong anymore
* explicitly `$destroy()` selectors and placeholders when re-rendering components (prevents a slow but steady bit of memory creep)
* as part of the `keep-alive` optimization, I updated the page list to re-fetch when re-activated (something @pfeytser was asking for)
