### ISSUE TITLE
Problem: Users who don't understand implications of removing ads delete ad components 

### ISSUE THREAD

**Issue by pfeytser** [clay/clay-kiln#1057]
Looks like a user deleted an ads component on Friday that led to some ad fires. 

How can this be avoided?

**Comment by vicfriedman** [comment]
Thanks for making this issue Peter! It definitely caused a huge issue, because it was a desktop layout level ad that was removed, which removed the ad instance from every single article. This deletion almost cost us a lot of money because TNT was supposed to have  ads running on all Golden Globes content, and were not seeing their ads there. 

As are as ads are concerned, dev is the only group ever making updates - ad ops doesn't actually even have Clay accounts, so we don't actually want other users to be able to add, remove, or edit ads in any way. Ad Dev usually makes those updates through PUTting the data anyway, so UI ability isn't even necessary for our workflow.

I don't know a whole lot about the Kiln internals, but there's no way to detect what component's are on the page based on component name or URI??

**Comment by nelsonpecora** [comment]
One thing I should probably point out: Editorial and Design _do_ actually add/remove `ad` components, when working with feature articles and cover stories. Whenever we've discussed blocking removal or doing other things based on component names, we've hit similar issues. Most use cases cover 75-90%, but nobody wants total consistency (which is a problem because Kiln's whole purpose is to make component editing totally consistent)

**Comment by nelsonpecora** [comment]
Per Peter, one idea that might work is a github-style "type the name of the component to confirm" delete confirmation. This would provide enough friction while still giving the users flexibility to delete things they actually want gone. This would have to be implemented via a reserved property in the schema, such as `_confirmRemoval: true`

**Comment by fraddski** [comment]
@nelsonpecora we've created a wrapper component for editorial/design to manually insert ad bundles in features, so there shouldn't be a need to delete the ad component itself through the UI.

We can definitely trial a confirmation feature, but if we still see ads being removed we will need to lock this down.

**Comment by nelsonpecora** [comment]
This needs more discussion, it seems

**Comment by nelsonpecora** [comment]
![screen shot 2018-01-03 at 11 35 55 am](https://user-images.githubusercontent.com/447522/34529539-6291e93c-f07a-11e7-869b-2c953a0096ce.png)
