### ISSUE TITLE
Scoped PubSub

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1075]
So imagine you have a component who wants to update it's children components with a value. Cool, pub/sub. 

But what if you have multiple instances of that component and you want to scope the property that is being pubbed to _only that component's children_.

Angular had an interesting concept on it's `$scope` object with `$emit` and `$broadcast` indicating "direction". I wonder how big of a lift something like this might be. The idea of scoping brings inherent complexity, but also could make components more flexible.

**Comment by vicfriedman** [comment]
This came up recently for a problem @fraddski and I were dealing with with the in-article-image-slideshow and in-article-image-slide components. We wanted to be able to have multiple slideshows on an article that each could have a different width, without make the user enter the width of the slideshow on each slide (becuase thats really tedious for the user)

So in our case, the slideshow knows it own width, but the slide doesn't, so the size of the slideshow is only selected one. Pubsub currently doesn't allow for multiple instances to publish different information to their own specific children, so we ended up just making it so all slideshows are of the same width on a single article.

**Comment by nelsonpecora** [comment]
Hmm, maybe something like:

```yaml
_publish:
  prop: fooBar
  scope: children # children | parents | all
```

**Comment by pfeytser** [comment]
scoped: true 

We only care about children.

**Comment by pfeytser** [comment]
* In Clay, children do not care about their parents, thus, they are not allowed to limit their publishing to only parents. 
* Parents may care about children, thus they are allowed to limit their subscribing to only children.

**Comment by nelsonpecora** [comment]
After chatting this through with Byron, there's a slight change:

* only add scope to `_publish`, not `_subscribe`
* `scope:` can be `parent`, `children`, or `global` (default)
* mvp of this functionality will be `!!querySelector('[data-uri="parent uri"] [data-uri="child uri"]')`, which can be used to find if anything is a parent or child component of anything else

**Comment by nelsonpecora** [comment]
There are two options we could choose for specifying scope:

1. instead of a string (or array of strings), specify the properties as objects (or arrays of objects), similar to the example above (`{ name: someProp, scope: children }`)
2. use a similar syntax to site-specificity / form sections (`_publish: someProp (children)`)

If we use option 2, how do we balance legibility vs efficiency? I.e. do we want to force devs to write out "children" and "parents" every time, or should it be shorter? (Personally I think that this use case is infrequent enough that we should defer to legibility)
