### ISSUE TITLE
Schedule Date

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1084]
When a page is scheduled, the time appears for the time picker but the date field is blank.

![screen shot 2018-01-11 at 3 11 40 pm](https://user-images.githubusercontent.com/4906712/34845133-db596a12-f6e1-11e7-80fa-a3fe3bd706c4.png)

**Comment by amycheng** [comment]
After looking into, I think this bug is caused by two colliding pieces of logic:
- date and time should be reset when the post is scheduled (this causes the date to be reset)
- the input value for the timepicker should always be updated on input change (this causes the time to be filled in even after the value is suppose to be reset)

I'll have to dig into the timepicker component to see if i can implement a fix there
