### ISSUE TITLE
Initials Are Backwards

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#1109]
![screen shot 2018-02-06 at 3 51 17 pm](https://user-images.githubusercontent.com/4906712/35883572-a56587be-0b55-11e8-8876-cf801e7b9966.png)

**Comment by nelsonpecora** [comment]
This is because the names that come from nymag's LDAP server specify themselves like that. Since they're in a single string (and [we can't assume that commas separate "first names" and "last names"](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)), that's expected behavior.

Oauth endpoints that specify names correctly (i.e. in the order that the names go in, which is also not something we can assume (thanks, 神武天皇)) don't have this side-effect.
