### ISSUE TITLE
update to webpack 4 + Jest

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#1153]
* webpack 4 is much, much faster
* webpack 4 supports a new build of uglify that works with es6
* we should remove the (horrendous) karma + browserstack test frameworks in favor of something fast and incremental like Jest

**Comment by amycheng** [comment]
I'm all for replacing Karma with Jest. I've looked into this a bit and here are my notes:

- the tests are expecting the `window` object, which Karma gives to us for free because it runs the tests in a browser. Jest does not run within the browser and we'll need to stub it. I've had middling success with [jsdom](https://github.com/jsdom/jsdom)
- [this](https://github.com/skovhus/jest-codemods) might be helpful in converting our existing Mocha specs to Jest specs
- [Vue Test Utils](https://vue-test-utils.vuejs.org/en/) is officially supported by Vue. The utils look good but I hit a wall using it with Karma but maybe it's better with Jest? Here's the [page](https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html) about testing SFCs with Jest

**Comment by nelsonpecora** [comment]
There's another project that just updated to webpack 4 + jest, and might be a useful reference: https://github.com/viljamis/vue-design-system/tree/3.0.0

**Comment by amycheng** [comment]
re: vue-design-system 
the tests are so clean!

So here are the Karma->Jest migration tasks that I think will be annoying:

- figuring out to build the files via webpack before testing them with Jest
- stubbing the `window` object
- converting the mocha tests into jest tests
