### ISSUE TITLE
Scheduled Publishing Date Menu Skips Month on Last Day of the Month

### ISSUE THREAD

**Issue by yuliyv** [clay/clay-kiln#1373]
We are seeing reports that on the last day of the month (for example January 31st) when users open the scheduled publishing panel (pictured below) and try to choose the date and do next month it will actually skip two months forward.  For example if the current date is January 31st and the users uses the `>` button to move forward one month it will actually put them into March (instead of Feburary)

![image](https://user-images.githubusercontent.com/1062604/52129509-b41cf780-2605-11e9-8c97-779bb309c412.png)

**Comment by scottnash** [comment]
The bug is in the Keen-UI/UIDatepicker itself.  You can reproduce the bug on the source site if you set your computer's date to the last day of a month.  https://josephuspaye.github.io/Keen-UI/#/ui-datepicker 

I created an issue with the bug on the KeenUI repo. https://github.com/JosephusPaye/Keen-UI/issues/434

**Comment by scottnash** [comment]
Keenu-UI datepicker has been patched to fix this bug.  Should just need to update to using the latest version of it to resolve this bug.
