### ISSUE TITLE
componentList enforced max length

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#298]
Component lists should have `min` and `max` arguments, and enforce them. This means:
- when the `min` number of components exist in a list, disallow deleting components
- when the `max` number of components exist in a list, disallow adding more components
- when either of these two states exist, maybe have an warning/error message (when you try to do the action, or just displayed)?

**Comment by TakenPilot** [comment]
Throwing popups is one of the worst UI patterns.  It interrupts the user flow and blocks the view of whatever caused the issue.

If the popup is to the side or above or below, it also distracts from the area where the user was working.

Better to just block the behavior.

**Comment by yoshokatana** [comment]
Yep, agreed.

**Comment by nelsonpecora** [comment]
There aren't really good ways to handle this consistently, and the use cases for it seem pretty small. We can re-open and revisit if needed.

**Comment by byronhulcher** [comment]
Officially declaring this issue RE-OPENED

**Comment by byronhulcher** [comment]
While we have soft `max` and `min` values which run on pre-publish, I'd like to have rules that align closer to the original features in this thread, preventing a user from adding or removing components.  My use case a component with a componentList that supports between 2-6 components. Fewer than 2, okay fine it looks empty, and we can have a placeholder. Larger than 6 though, i need to create a new section of the template for `overflow` components where they can be edited/removed.  Otherwise they're lost through the UX and could possibly block publishing if I created a child component off-page and now no longer can edit it.  Creating an overflow component-list means adding extra logic to the schema and either model or template to deal with what is really an editing concern imo.  So I'm not so concerned about a hard minimum, but I can definitely use a hard maximum.

**Comment by nelsonpecora** [comment]
I think if we limited the scope of this to simply hiding the remove / add (+copy/duplicate) buttons based on the hard min/max, that'd work. We need a better config for it, though.

```yaml
_componentList:
  include:
    - foo-bar
    - baz-qux
  validate:
    min: 2
    max: 6
```

That currently sets prepublish validation on the list. Are there any situations where we'd want to have a _separate_ hard limit, or would it be ok to also make that the hard limit? (another thing to consider: other inputs have `min`/`max` validation, but that does _not_ set hard limits)

**Comment by byronhulcher** [comment]
After office hours discussion, lets just go forward with a `enforceMaxLength` for component lists, and drop the requirement for a min length, since it would be weird to have added components and be unable to remove them unless you added more.

**Comment by nelsonpecora** [comment]
Since we're dropping the `min` requirement and using an already-existing argument (and not adding extra UI affordances, simply removing the relevant buttons) I'm dropping this down to a 1 estimate.
