### ISSUE TITLE
datetime behavior

### ISSUE THREAD

**Issue by nelsonpecora** [clay/clay-kiln#817]
* not `datetime-local`
* needs custom implementation, since it's not supported natively in browsers
* perhaps we should change _all_ date/time behaviors/inputs to use a consistent implementation

**Comment by mheiber** [comment]
notes that might help for implementation:

- The browser's `&lt;input type="date":gt;` thingy (not supported in Firefox) uses this format: 'YYYY-MM-DDTHH:mm'.
- If `el` is an `&lt;input type="date":gt;`, then `el.value` will be a local date string (the date with timezone info stripped out).
- Converting a timezoneless dateString to a timezoned date can be done like this:

```
const MILLISECONDS_IN_MINUTE = 60 * 1000
const localDateStringToDate = localDateString => {
  const date = new Date(localDateString)
  date.setTime( date.getTime() + date.getTimezoneOffset() * MILLISECONDS_IN_MUTE)
  return date
}
```
because these APIs are reasonable, of course!

**Comment by nelsonpecora** [comment]
Kiln 5.0 comes with a material-design `datepicker` input, as well as a simple (but standardized) `timepicker` input. The `timepicker` uses a little bit of Natural Language Processing to smooth out the UX issues around different formats, so users can simply type in the format that makes the most sense for them (e.g. `5pm`, `5:00 PM`, `17:00`, etc)
