### ISSUE TITLE
Additional WYSIWYG Support

### ISSUE THREAD

**Issue by jonwinton** [clay/clay-kiln#875]
Slate friends asked about supporting the following:

- Special characters
- Emojis
- Special colors for text

Can we do the following:

- [ ] Confirm if they're already supported
- [ ] Confirm documentation talks about all three cases
- [ ] Begin discovery of these features if they aren't supported

**Comment by nelsonpecora** [comment]
Hmm, my initial thoughts are that special characters / emoji are better handled through the OS, since windows / macos / ios / android all have wildly different (but universally-supported) ways of dealing with these. Adding them to the wysiwyg would require both 1) reinventing the wheel (poorly, in the case where the native input is superior to anything we could do) and 2) forcing us do decide which special characters / emoji should be supported. It might also cause unforeseen conflicts with things like emoji pickers (via extensions/plugins) or [userland apps](http://matthewpalmer.net/rocket/)

Colorized text is a different case, and [Quill already supports it out of the box](https://quilljs.com/docs/formats/).
