### ISSUE TITLE
Bug: adding links via the WYSIWG editor can be a broken experience

### ISSUE THREAD

**Issue by amycheng** [clay/clay-kiln#923]
## Bug

- highlight text
- select the link
- either paste/type in the link
- clicking away DOESN'T save the link, you need to hit enter (this UX doesn't match the other UX of saving other components)
- when highlighting the same link after a successful save, the recently entered link does not appear

**Comment by nelsonpecora** [comment]
For the first issue, clicking away doesn't save links in Quill. [I opened a ticket against Quill to track this](https://github.com/quilljs/quill/issues/1797). For the second issue, there was a css error that was fixed in Kiln 4.x, so you should be able to preview links after they're added now. (Mouseover the link to see the preview tooptip)
